version: '3.3'

services:
  infomate_app:
    build:
      context: .
      args:
        requirements: requirements.txt
    command: make docker_run
    container_name: infomate_app
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    image: postgres:11
    container_name: infomate_postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=infomate
    ports:
        - 5432
